controller:
  nodeSelector:
    kubernetes.io/arch: "arm64"

  resources:
    requests:
      cpu: "300m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1.5Gi"

  image:
    repository: "jenkins/jenkins"
    tag: "2.479.3-jdk17" 
    pullPolicy: Always
    
  overwritePlugins: true
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - github
    - docker-workflow
    - docker-commons
    - pipeline-stage-view
    
  javaOpts: "-Xmx1024m -Xms512m -Djava.awt.headless=true -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"
  jenkinsOpts: "--prefix=/" 
  serviceType: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hostName: jenkins.yourdomain.com
    paths:
      - path: /
        pathType: Prefix

# 🚨 MOVED TO THE ROOT LEVEL 🚨
persistence:
  enabled: true
  existingClaim: "jenkins-0" 

agent:
  enabled: true
  image: 
    repository: "jenkins/inbound-agent" 
    tag: "latest"
    pullPolicy: Always
  nodeSelector:
    kubernetes.io/arch: "arm64"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"