loki:
  enabled: true
  image:
    tag: 2.9.11
  isDefault: false # Only needed if you have other log sources
  nodeSelector:
    kubernetes.io/arch: arm64
  namespace: monitoring
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 20Gi
    accessModes:
      - ReadWriteOnce

promtail:
  enabled: true