prometheus:
  prometheusSpec:
    # Reduce retention so you don't fill your disk immediately
    retention: 10d
    retentionSize: 10GB
    
    # Target your Raspberry Pis instead of the Mini PC
    nodeSelector:
      kubernetes.io/arch: arm64

    resources:
      requests:
        memory: 400Mi  # Note: Use 'Mi', not 'mi'
        cpu: 100m
      limits:
        memory: 1Gi
        
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

# 2. Configure Grafana Storage
grafana:
  enabled: true
  nodeSelector:
    kubernetes.io/arch: arm64
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://monitoring-stack-loki.monitoring.svc.cluster.local:3100
      version: 1
      editable: false
  ingress:
    enabled: true
    ingressClassName: traefik  # Tells K3s to use Traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - grafana.jirivasm.dev
    path: /

  persistence:
    enabled: true
    storageClassName: longhorn
    accessModes: ["ReadWriteOnce"]
    size: 10Gi


# 3. Disable Alertmanager storage (Optional, keeps it simple)
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi