apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vending-deployment.yaml
  - vending-service.yaml
  - vending-ingress.yaml
  # Add any other YAML files you have for this app here

images:
- name: jrivas/vending-machine  # THIS MUST MATCH YOUR DEPLOYMENT IMAGE NAME EXACTLY
  newName: jrivas/vending-machine
  newTag: latest