apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scraper-app
  namespace: devops-tools # Stays in your management namespace
spec:
  project: default
  source:
    repoURL: git@github.com:jirivasm/WorkSearch.git
    targetRevision: HEAD
    path: . 
  destination:
    server: https://kubernetes.default.svc
    namespace: scraper # Where the CronJob will be deployed
  syncPolicy:
    automated:
      prune: false
      selfHeal: true