apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-scraper-cron
  namespace: scraper
spec:
  # Runs every morning at 8:00 AM server time
  schedule: "0 8 * * *"
  # Keeps the logs of the last 3 successful runs and 1 failed run to save space
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-scraper
            image: jirivasm/job-scraper:latest
            # Forces K8s to always pull the newest image from Docker Hub
            imagePullPolicy: Always 
            env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: scraper-secrets
                  key: GEMINI_API_KEY
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: scraper-secrets
                  key: DISCORD_WEBHOOK_URL
          # If the script crashes (e.g., network error), K8s will try running it again
          restartPolicy: OnFailure