controller:
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  javaOpts: "-Xmx384m -Xms256m"
  
  image:
    repository: jirivasm/custom-jenkins
    tag: "latest"
    pullPolicy: Always
  overwritePlugins: true
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - docker-commons
    - pipeline-stage-view
  # Use these specific keys for the chart to merge your options
  javaOpts: "-Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"
  jenkinsOpts: "--prefix=/" 
  persistence:
    enabled: true
    existingClaim: "jenkins-pvc"
  serviceType: ClusterIP