apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vending-deployment.yaml
  - vending-service.yaml
  - vending-ingress.yaml
  - vending-pvc.yaml
  # Add any other YAML files you have for this app here

images:
- name: jirivasm/vending-app  # THIS MUST MATCH YOUR DEPLOYMENT IMAGE NAME EXACTLY
  newName: jirivasm/vending-app
  newTag: latest