# vending-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vending-machine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vending-machine
  template:
    metadata:
      labels:
        app: vending-machine
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: vending-app
        image: jirivasm/vending-app:latest
        resources:
          requests:
            memory: "128Mi"  # Bare minimum RAM needed to start Flask
            cpu: "100m"      # 1/10th of a CPU core
          limits:
            memory: "256Mi"  # Hard cap. Kills the pod if it eats more than 256MB
            cpu: "250m"
        env:
        - name: DB_HOST
          # The internal DNS name we found earlier
          value: "postgresql.database.svc.cluster.local"
        - name: DB_USER
          value: "postgres"
        - name: DB_NAME
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              # Point to the SAME secret pgAdmin is using
              name: postgres-auth-secret
              key: postgres-password
        - name: APP_STACK
          value: "Python | Flask | Postgres| Jenkins | Kubernetes | ArgoCD | Longhorn | Cloudflare | Prometheus | Grafana | Loki"
        ports:
        - containerPort: 5001