apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: vending-dev

# Use a prefix to distinguish Dev pods from Prod pods
namePrefix: dev-

# Dev usually needs fewer resources
patches:
# 1. Patch the Deployment for 1 replica (Save resources in the lab)
- target:
    kind: Deployment
    name: vending-machine
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: vending-machine
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: vending-app 
            env:
            - name: DB_HOST
              value: "postgres-db-postgresql"
            - name: DB_USER
              value: "postgres"
            # ADD THIS BLOCK BELOW:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: postgres-password
# 2. Patch the Ingress for your Dev Cloudflare URL
- target:
    kind: Ingress
    name: vending-ingress
  patch: |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: vending-ingress
    spec:
      rules:
      - host: dev-vending.jirivasm.dev