apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: vending-dev

# Use a prefix to distinguish Dev pods from Prod pods
namePrefix: dev-

# Dev usually needs fewer resources
patches:
- target:
    kind: Deployment
    name: vending-machine
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1