persistence:
  enabled: true
  storageClass: "longhorn" # Use your Chicago home lab storage
  accessMode: ReadWriteOnce
  size: 1Gi # pgAdmin configuration is very small; 1GB is plenty
env:
  email: "jirivasmo@gmail.com"
  password: "pgadmin-web-auth" 
  passwordSecretKey: "admin-password" # This is for the UI login

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik # K3s uses Traefik by default
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # If you use cert-manager
  hosts:
    - host: pgadmin.jirivasm.dev # Your Cloudflare domain
      paths:
        - path: /
          pathType: Prefix