apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-auth-bridge
  namespace: vending-dev # Match your app namespace
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-auth-secret # Matches your postgres-values.yaml
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgres-auth
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-auth-bridge
  namespace: vending-prod # Your Production Namespace
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-auth-secret
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgres-auth
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-auth-bridge
  namespace: vending-dev
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-web-auth # Matches your pgadmin-values.yaml
  data:
    - secretKey: admin-password
      remoteRef:
        key: pgadmin-auth
        property: admin-password