apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sync-discord-webhook
  namespace: k8sgpt-operator-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    # Points to your existing Vault connection
    name: vault-backend 
    kind: ClusterSecretStore
  target:
    # The name of the secret this will create for K8sGPT to use
    name: discord-webhook 
  data:
    - secretKey: url
      remoteRef:
        # The path to the secret inside your HashiCorp Vault
        key: k8s-discord 
        property: discord-webhook