apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
stringData:
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "SuperSecretPassword123"
  # This is the "secret sauce" for MinIO:
  AWS_ENDPOINTS: "10.0.0.34:9000"