apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scraper-secrets-sync
  namespace: scraper
spec:
  refreshInterval: "5m" # Check for updates every 5 mins
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: scraper-secrets # The name of the secret your CronJob expects
    creationPolicy: Owner
  data:
  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: gemini # The path name you created in the Vault UI
      property: GEMINI_API_KEY
  - secretKey: DISCORD_WEBHOOK_URL
    remoteRef:
      key: discord
      property: DISCORD_WEBHOOK_URL
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.hashicorp.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: external-secrets
