apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scraper-secrets-sync
  namespace: scraper
spec:
  refreshInterval: "5m" # Check for updates every 5 mins
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: scraper-secrets # The name of the secret your CronJob expects
    creationPolicy: Owner
  data:
  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: secret # The path name you created in the Vault UI
      property: GEMINI_API_KEY
  - secretKey: DISCORD_WEBHOOK_URL
    remoteRef:
      key: worksearch
      property: DISCORD_WEBHOOK_URL